title: Je hurle
description: >-
  Blog d'une féministe radicale (et misandre)
author: Lou Dorge
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jehurle.com"
lang: fr

sass:
  sass_dir: _sass

theme: minima
plugins:
  - jekyll-feed

minima:
  date_format: "%d/%m/%Y"
permalink: /:year/:month/:day/:title/
show_excerpts: true

exclude:
  - docker-compose.yml
  - Makefile
  - gem
  - .github
  - README.md
